[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v 
    --tb=short
    --memray
    --memray-bin-path=memray-logs
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    limit_memory: marks tests with memory limits
